"""add ai mcp credentials table

Revision ID: 769a8c5298d4
Revises: f030f9e91731
Create Date: 2026-09-04 14:00:43.157567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769a8c5298d4'
down_revision: Union[str, None] = 'f030f9e91731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_mcp_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=4096), nullable=False),
    sa.Column('refresh_token', sa.String(length=4096), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_mcp_credentials')
    # ### end Alembic commands ###
