"""init

Revision ID: 8d7c2ac1bb85
Revises: 
Create Date: 2026-09-04 12:41:24.914727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7c2ac1bb85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('planned_release_date', sa.Date(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('stage', sa.Enum('IDEA', 'GATHERING', 'EDITING', 'RELEASE', 'ANALYSIS', name='content_stage'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('raw_texts', sa.Text(), nullable=True),
    sa.Column('raw_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_texts', sa.Text(), nullable=True),
    sa.Column('analysis_notes', sa.Text(), nullable=True),
    sa.Column('analysis_reach', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CLIENT', 'PRODUCTION', 'INSTALLATION', 'COMPLETED', name='cycle_status'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WORKER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('warehouse_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('supplier_contact', sa.String(length=255), nullable=True),
    sa.Column('supplier_phone', sa.String(length=64), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quantity_in_stock', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_assignees',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'user_id')
    )
    op.create_table('file_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('path_on_disk', sa.String(length=500), nullable=False),
    sa.Column('purpose', sa.Enum('CONTRACT', 'HOUSE_PROJECT', 'TASK_IMAGE', 'MARKETING_RAW', 'MARKETING_FINAL', name='file_purpose'), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('DELIVERY', 'INSTALLATION', 'FOLLOWUP', name='installation_stage'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('post_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_material_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.Enum('SUPPLY', 'ISSUED', 'REQUIRED_ADJUSTED_UP', 'REQUEST_REJECTED_RETURN', 'MANUAL_ADJUST', name='stock_movement_reason'), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_material_id'], ['warehouse_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_module_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.Enum('CLIENTS', 'PRODUCTION', 'INSTALLATION', 'CYCLE', 'WAREHOUSE', 'MARKETING', 'TASKS', name='module'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module', name='uq_user_module')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('LEAD', 'DISCUSSION', 'APPROVAL', 'PAYMENT', 'POSTPAYMENT', name='client_stage'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=32), nullable=False),
    sa.Column('passport_number', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('wishes_description', sa.Text(), nullable=True),
    sa.Column('estimated_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('house_area', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('layout_notes', sa.Text(), nullable=True),
    sa.Column('project_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('installation_address', sa.String(length=500), nullable=True),
    sa.Column('contract_file_id', sa.Integer(), nullable=True),
    sa.Column('house_project_file_id', sa.Integer(), nullable=True),
    sa.Column('documents_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('payment_locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_file_id'], ['file_assets.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['house_project_file_id'], ['file_assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('content_final_files',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'file_id')
    )
    op.create_table('content_raw_files',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['file_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'file_id')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['production_id'], ['productions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_material_id'], ['warehouse_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_material_id', sa.Integer(), nullable=False),
    sa.Column('inventory_number', sa.String(length=64), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('quantity_required', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('quantity_provided', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_material_id'], ['warehouse_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('NOT_READY', 'READY', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('link_type', sa.Enum('NONE', 'CLIENT_STAGE', 'CONTENT_STAGE', 'WAREHOUSE_REQUEST', 'WAREHOUSE_SHORTAGE', name='task_link_type'), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('link_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_material_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='material_request_status'), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['module_material_id'], ['module_materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['warehouse_material_id'], ['warehouse_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_assignees',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_id')
    )
    op.create_table('task_images',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'file_id')
    )
    op.create_table('task_reviewers',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_reviewers')
    op.drop_table('task_images')
    op.drop_table('task_dependencies')
    op.drop_table('task_assignees')
    op.drop_table('material_requests')
    op.drop_table('tasks')
    op.drop_table('module_materials')
    op.drop_table('client_notes')
    op.drop_table('supply_lines')
    op.drop_table('modules')
    op.drop_table('content_raw_files')
    op.drop_table('content_final_files')
    op.drop_table('clients')
    op.drop_table('user_module_access')
    op.drop_table('supplies')
    op.drop_table('stock_movements')
    op.drop_table('productions')
    op.drop_table('post_links')
    op.drop_table('installations')
    op.drop_table('file_assets')
    op.drop_table('content_assignees')
    op.drop_table('warehouse_materials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('cycles')
    op.drop_table('content_items')
    # ### end Alembic commands ###
