"""add ai module value and ai chat tables

Revision ID: f030f9e91731
Revises: 8d7c2ac1bb85
Create Date: 2026-09-04 13:42:58.031123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f030f9e91731'
down_revision: Union[str, None] = '8d7c2ac1bb85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New Module.AI access-grant value. Autogenerate doesn't detect added
    # enum values on an existing pg enum type, so this is added by hand.
    # Not inside the surrounding implicit transaction's DDL batch with a
    # dependent use, so PG16 allows ADD VALUE here without extra ceremony.
    op.execute("ALTER TYPE module ADD VALUE IF NOT EXISTS 'AI'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.Enum('CLIENTS', 'PRODUCTION', 'CYCLE', 'WAREHOUSE', 'MARKETING', 'TASKS', 'GENERAL', name='ai_chat_domain'), nullable=False),
    sa.Column('mode', sa.Enum('NO_ACTIONS', 'REQUIRE_APPROVAL', 'AUTO_APPROVE', name='ai_chat_mode'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('tool_resolutions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_pending_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('tool_use_id', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('tool_input', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='ai_pending_action_status'), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['ai_chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['ai_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_pending_actions')
    op.drop_table('ai_messages')
    op.drop_table('ai_chats')
    # ### end Alembic commands ###
    # Note: Postgres has no DROP VALUE for enums, so the 'AI' value added to
    # the `module` type in upgrade() is intentionally left in place here.
